src/Entity/Mark.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MarkRepository")
 */
class Mark
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="float")
     * @Assert\NotBlank()
     * @Assert\Length(
     *      min = 1,
     *      max = 25,
     *      minMessage = "Die Beschreibung muss mindestens {{ limit }} Zeichen lang seien",
     *      maxMessage = "Die Beschreibung darf nicht länger als {{ limit }} Zeichen lang seien"
     * )
     */
    private $mark;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Subject", inversedBy="marks")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotBlank()
     */
    private $subject;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $changed_at;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_active;

    /**
     * @ORM\Column(type="float")
     */
    private $weight;

    public function __construct() {
        $this->created_at = new \Datetime();
        $this->is_active = true;
        $this->weight = 1;
    }

    public function getId()
    {
        return $this->id;
    }

    public function getMark(): ?float
    {
        return $this->mark;
    }

    public function setMark(float $mark): self
    {
        $this->mark = $mark;

        return $this;
    }

    public function getSubject(): ?Subject
    {
        return $this->subject;
    }

    public function setSubject(?Subject $subject): self
    {
        $this->subject = $subject;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getChangedAt(): ?\DateTimeInterface
    {
        return $this->changed_at;
    }

    public function setChangedAt(?\DateTimeInterface $changed_at): self
    {
        $this->changed_at = $changed_at;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(bool $is_active): self
    {
        $this->is_active = $is_active;

        return $this;
    }

    public function getWeight(): ?float
    {
        return $this->weight;
    }

    public function setWeight(float $weight): self
    {
        $this->weight = $weight;

        return $this;
    }
}

src/Controller/YearController.php
<?php

namespace App\Controller;

use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Validator\Validator\ValidatorInterface;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Translation\TranslatorInterface;

use App\Entity\SchoolYear;
use App\Entity\Subject;
use App\Entity\Template;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class YearController extends Controller
{

    private $translator;

    public function __construct(TranslatorInterface $translator) {
        $this->translator = $translator;
    }
    /**
     * @Route("/year", name="year")
     */
    public function index()
    {
        $entityManager = $this->getDoctrine()->getManager();
        $repository = $this->getDoctrine()->getRepository(SchoolYear::class);
        $schoolyears = $repository->findBy(['user' => $this->getUser()]);
        $highlights = $this->get('session')->getFlashBag()->get('highlight');
        return $this->render('year/index.html.twig', compact('schoolyears', 'highlights'));
    }

    /**
     * @Route("/year/edit/{year}", name="year_edit")
     */
    public function edit(SchoolYear $year, Request $request) {
        $form = $this->createFormBuilder($year)
        ->add('name', TextType::class, ['label' => 'Name'])
        ->add('speichern', SubmitType::class, ['label' => 'Speichern'])
        ->getForm();
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $formData = $form->getNormData();
            $year->setName($formData->getName());
            $year->setChangedAt(new \Datetime());
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($year);
            $entityManager->flush();
            $this->addFlash('success', 'Änderung erfolgreich!');
            $this->addFlash('highlight', $year->getId());
            return $this->redirectToRoute('year');
        }
        $form = $form->createView();

        return $this->render('year/edit.html.twig', compact('form', 'year'));

        return $this->json([$year->getId()]);
    }

    /**
     * @Route("/year/add", name="year_add")
     */
    public function add(Request $request) {
        $entityManager = $this->getDoctrine()->getManager(); 
        $subjectRepository = $this->getDoctrine()->getRepository(Subject::class);
        $templateRepository = $this->getDoctrine()->getRepository(Template::class);
        $templates = $templateRepository->findBy(['is_global' => true, 'is_active' => true]);
        $form = $this->createFormBuilder(new SchoolYear())
            ->add('name', TextType::class, ['label' => 'Name'])
            ->add('subjects', EntityType::class, [
                'label' => 'Fächer',
                'class' => Template::class,
                'choices' => $templates,
                'multiple' => true,
                'required' => false,
                'help' => 'Bei den hier gezeigten Fächern handelt es sich lediglich um einige Fächer welche oft genutzt werden. Eigene Fächer kannst du nach dem Erstellen des Schuljahres anlegen.',
                'choice_label' => function ($template)  {
                    return $template->getName();
                },
                'choice_value' => function (Template $template = null) {
                    return $template ? $template->getName() : '';
                }
                ])
            ->add('save', SubmitType::class, ['label' => 'Hinzufügen'])
            ->getForm();
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $formData = $form->getNormData();
            $subjects = $formData->getSubjects();
            $formData->removeAllSubjects();
            $formData->setUser($this->getUser());
            $entityManager->persist($formData);
            foreach ($subjects as $_subject) {
                $subject = new Subject();
                $subject->setName($_subject->getName());
                $formData->addSubject($subject);
                $entityManager->persist($subject);
                $entityManager->flush();
            }
            $entityManager->flush();

            return $this->redirectToRoute('year');
        }
        $form = $form->createView();
        return $this->render('year/add.html.twig', compact('form'));
    }
}

templates/year/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% trans %}Neues Schuljahr hinzufügen{% endtrans %}{% endblock %}

{% block body %}

<div class="container">
    <br>
    <h1>{% trans %}Neues Schuljahr hinzufügen{% endtrans %}</h1>
    <br>
    {{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}
</div>
{% endblock %}

templates/year/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% trans with {'%yearName%': year.name} %}Schuljahr %yearName% bearbeiten{% endtrans %}{% endblock %}

{% block body %}
<div class="container">
    <h1>{% trans with {'%yearName%': year.name} %}Schuljahr %yearName% bearbeiten{% endtrans %}</h1>

    {{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}
</div>
{% endblock %}

templates/year/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% trans %}Deine Schuljahre{% endtrans %}{% endblock %}

{% block body %}
<div class="container">
    <br>
    <h1>{% trans %}Deine Schuljahre{% endtrans %}</h1>
    <a href="{{path("year_add")}}"><i class="fas fa-plus-square"></i> {% trans %}Neues Schuljahr{% endtrans %}</a>
    <br>
    <br>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">{% trans %}Name{% endtrans %}</th>
                <th scope="col">{% trans %}Erstellt{% endtrans %}</th>
                <th scope="col">{% trans %}Letzte Änderung{% endtrans %}</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for year in schoolyears %}
                <tr{% if year.id in highlights %} class="table-info"{% endif %}>
                    <td>{{year.name}}</td>
                    <td>{{year.createdAt|date('Y-m-d G:i:s')}}</td>
                    <td>{{year.changedAt|date('Y-m-d G:i:s')}}</td>
                    <td><a href="{{path('year_edit', {'year': year.id})}}"><i class="fas fa-edit"></i></a> <a href="{{path("subject_list_all", {'year': year.id})}}"><i class="fas fa-table"></i></a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}